#!/bin/sh
# Script used to deploy the Covid-19 application to the AWS Lambda Serverless framework
# NOTE: You will need to choose a unique 3s bucket name ('covid19plus' is used here)

echo "\n\nAbout to deploy the Lambda application\n\n"
mvn clean package
aws cloudformation delete-stack --stack-name covid19plus
aws cloudformation package --template-file sam.yml --output-template-file output-sam.yml --s3-bucket covid19plus
aws cloudformation deploy --template-file output-sam.yml --stack-name covid19plus --capabilities CAPABILITY_IAM
echo "\n\nLambda application deployed succesfully!\n\n"

export END_POINT=`aws cloudformation describe-stacks --stack-name covid19plus --query 'Stacks[0].Outputs[0].OutputValue'`
echo  END POINT for Lambda API Gatway: $END_POINT

echo "\n\nAbout to deploy the static s3 website\n\n"
cd react-hooks-frontend
echo "/* This File was automatically generated by deploy.sh */\nexport const getEndPoint = () => {\n  return $END_POINT\n}" > src/utils/config.js
npm run build
cd build
cp index.html about.html
cp index.html signup.html
cp index.html admin.html
aws s3 rm --recursive s3://virus19
aws s3 sync . s3://virus19
echo "\n\nThe Lambda Application and the 3s static website were setup successfully!\n\n"