AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.idk::covid19
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  Covid19Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.idk.covid19.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/covid19-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Timeout: 40
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  Covid19Api:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: Covid19Api
