spring:
  cache:
    cache-names: rapidApi
    caffeine:
      spec: maximumSize=500,expireAfterAccess=10m

server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG
    com.idk: DEBUG

covid19:
  api-version: /api/1.0
  admin-access:
    name: admin
    password: admin
  api-host: covid-193.p.rapidapi.com
  api-key: cb1f09fd7dmsh35f7dd8afd27dfdp191e0cjsnca765ccf022a
