server:
  port: 8080

spring:
    security:
      user:
        name: admin
        password: admin

logging:
  level:
    org.springframework: DEBUG
    com.idk: DEBUG

covid19:
  api-version: /api/1.0
